apiVersion: apps/v1
kind: Deployment
metadata:
  name: me-app2
  labels:
    app: me-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me-app2
  template:
    metadata:
      labels:
        app: me-app2
    spec:
      containers:
      - name: me-app2
        image: ghcr.io/magicsong/magicsong-app2:latest  # 使用您的镜像仓库地址替换这里
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        envFrom:
        - secretRef:
            name: app-secret
        env:
        - name: NODE_ENV
          value: "production"
        - name: AUTH_TRUST_HOST
          value: "true"
        - name: NEXT_PUBLIC_ALLOW_BACKFILL
          value: "true"  

---
apiVersion: v1
kind: Service
metadata:
  name: me-app-service2
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: me-app2
  ports:
  - port: 8080
    targetPort: 3000
  type: LoadBalancer

